name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.13.x
          lhci collect --url=http://localhost:3000 --staticDistDir=./build --numberOfRuns=3 --output=./report.json
          jq -r '.[0].audits[] | "\(.title): \(.displayValue)"' ./report.json > lighthouse-report.txt
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add lighthouse-report.txt
          git commit -m "Add Lighthouse report"
          git push